[package]
name = "from_trait"
version = "0.1.0"
authors = ["Francesco Piantini <francesco.piantini@thalesgroup.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
